<?php
$q = "ALTER TABLE user ADD full_name VARCHAR(266) NOT NULL AFTER username";
$q = "ALTER TABLE user ADD photo VARCHAR(500) NOT NULL DEFAULT '' AFTER full_name";

$q = "CREATE TABLE vehicle (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    model_id SMALLINT UNSIGNED NOT NULL,
    frame_number VARCHAR(20) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;";

$q = "CREATE TABLE brand (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;";

$q = "CREATE TABLE model (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    brand_id SMALLINT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;";

$q = "CREATE TABLE client (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(15) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;";

$q = "CREATE TABLE job (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    client_id SMALLINT UNSIGNED NOT NULL,
    vehicle_id SMALLINT UNSIGNED NOT NULL,
    creator_id SMALLINT UNSIGNED NOT NULL COMMENT 'User id',
    performer_id SMALLINT UNSIGNED DEFAULT 0 COMMENT 'User id',
    created_at DATETIME,
    status ENUM('new', 'on-the-job', 'pending', 'done','closed') DEFAULT 'new',
    addition TEXT COMMENT 'Additional Information',
    pay INT(1) UNSIGNED NOT NULL DEFAULT 0,
    done_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;";

$q = "ALTER TABLE job ADD done_at DATETIME DEFAULT NULL";

$q = "CREATE TABLE task (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	job_id SMALLINT UNSIGNED NOT NULL,
    name TEXT NOT NULL,
    price FLOAT DEFAULT 0,
    performer_percent TINYINT DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=utf8;";

$q = "ALTER TABLE task ADD price FLOAT DEFAULT 0";
$q = "ALTER TABLE task ADD performer_percent TINYINT DEFAULT 0";

$q = "CREATE TABLE job_log (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    job_id SMALLINT UNSIGNED NOT NULL,
    info VARCHAR(255) NOT NULL,
    created_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;";

$q = "CREATE TABLE parts (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    job_id SMALLINT UNSIGNED NOT NULL,
    name TEXT NOT NULL,
    price FLOAT DEFAULT 0,
    quantity SMALLINT UNSIGNED NOT NULL DEFAULT 1
) ENGINE=MyISAM DEFAULT CHARSET=utf8;";